import Head from "next/head";

import styles from "../styles/Home.module.css";
import { useState } from "react";
export default function Home() {
  const [hosted_url, setHosted_url] = useState("");

  let chargeData = {
    name: `treeNumber trees for cryptoNumber currentCrypto `,
    description: 1,
    local_price: {
      amount: 0.0000001,
      currency: `btc`,
      //case sensitive?
    },
    pricing_type: "fixed_price",
    metadata: {
      user: "testemail@example.con",
    },
  };
  async function coinbaseConnect() {
    console.log("coninbase btn pressed called");
    const res = await fetch("/api/createCharge", {
      method: "POST",
      body: JSON.stringify(chargeData),
    });
    let data = await res.json();
    console.log("data: ", data);
    setHosted_url(data["hosted_url"]);
    console.log(hosted_url);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>API TEST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen flex flex-col items-center justify-center ">
        <div className="md:w-1/3 flex flex-col items-center justify-center">
          <h1>Yo This is a test</h1>

          {hosted_url ? (
            <>
              <a
                href={hosted_url}
                className="mt-20 text-white font-semibold bg-[#1EC7D5] py-3 mx-2 rounded-2xl w-full text-center shadow-2xl hover:bg-red-500"
              >
                PAY
              </a>
              <h2>{hosted_url}</h2>
            </>
          ) : (
            <a
              onClick={() => coinbaseConnect()}
              className="mt-20 text-white font-semibold bg-[#1EC7D5] py-3 mx-2 rounded-2xl w-full text-center shadow-2xl hover:bg-red-500"
            >
              Swap
            </a>
          )}
        </div>
      </main>
    </div>
  );
}
