import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
export default function Home() {
  const [hosted_url, setHosted_url] = useState("");

  let chargeData = {
    name: `treeNumber trees for cryptoNumber currentCrypto `,
    description: 1,
    local_price: {
      amount: 0.0000001,
      currency: `btc`,
      //case sensitive?
    },
    pricing_type: "fixed_price",
    metadata: {
      user: "testemail@example.con",
    },
  };
  async function coinbaseConnect() {
    console.log("coninbase btn pressed called");
    const res = await fetch("/api/createCharge", {
      method: "POST",
      body: JSON.stringify(chargeData),
    });
    let data = await res.json();
    console.log("data: ", data);
    setHosted_url(data["hosted_url"]);
    console.log(hosted_url);
    // window.location.assign(`${hosted_url}`);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Yo This is a test</h1>

        {hosted_url ? (
          <a
            href={hosted_url}
            className="text-white font-semibold bg-[#1EC7D5] py-3 mx-2 rounded-2xl w-full text-center shadow-2xl"
          >
            PAY
          </a>
        ) : (
          <a
            onClick={() => coinbaseConnect()}
            className="text-white font-semibold bg-[#1EC7D5] py-3 mx-2 rounded-2xl w-full text-center shadow-2xl"
          >
            Swap
          </a>
        )}
      </main>
    </div>
  );
}
